### PR TITLE
Flattened registry mode

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes

The changes should allow to use registry in Flattened mode.
This should speed up the Registry, in cases when nested access to Data does not needed.

### Testing Instructions

Unit testing passes.

### Documentation Changes Required

New parameters for Registry constructor, that enable Flattened mode.

### CODE REVIEW

**Comment by HLeithner** [comment]
I'm not sure if this is a good idea, having a class behaving different without being able to check what method is uses.

also I think this should be it's own class, maybe extend `Registry` from a base class which doesn't implement `deep merge`. Also it could be interesting to convert between both methods...

But as this pr is I don't think it's a good approach tbh.

**Comment by Fedik** [comment]
>  having a class behaving different without being able to check what method is uses.

Can add method to check it, if realy need.

>  this should be it's own class, maybe extend Registry from a base class which doesn't implement deep merge.

Also as an option, I can make as own class.
This basiclay write another Registry class, because almost all methods in Registry doing "deep check".

Any other opinions? :)

**Comment by Fedik** [comment]
Maybe as alternative way, can do check for non empty separator before each call of:
```
strpos($path, $separator);
explode($separator, $path); 
```

This will be kind of the same (but not really).

Currently "empty separator" will cause error.

**Comment by Fedik** [comment]
I made PR for empty separator #66

**Comment by Fedik** [comment]
The pr for a new class #67 for flat registry

**Comment by HLeithner** [comment]
Looks good but I noticed that $data is a stdClass no idea why. Also I would make this class final.

**Pull request closed without merging**
