### PR TITLE
Support of un-associative arrays read/write

### PR DESCRIPTION
**Pull request by rkgrep**
Not well optimized, but I finally got it working.
My previous solution malformed output JSON code. This does not.

### CODE REVIEW

**Comment by mbabker** [comment]
So coming back around to this, apparently it's causing data to be returned in a different format in some cases (what was once an object is now an array).  Complicating matters is PHP's handling of `stdClass` with `get_object_vars()`, see http://3v4l.org/XeeQ7.

Any suggestions by chance?  Otherwise, it's looking like we'll have to look for an alternate approach to this or back it out completely.

**Comment by rkgrep** [comment]
I guess `get_object_vars` does not handle invalid PHP variable identifiers, while there are some cases like `(object) [1,2,3]`, whicn can generate invalid identifiers without errors.

As far as Registry is used to store only structures of scalar values (on the lowest level), we possibly can force all objects to be converted to arrays in the first place.

**Comment by asika32764** [comment]
I agree to rewrite inner store to array, is there any B/C concern?

**Comment by rkgrep** [comment]
1.x was mostly experimental so far. I think we shouldn't care about compatibility in 2.x

**Comment by mbabker** [comment]
For 1.x I think the only concern is if someone's extending Registry and
accessing the data store directly.  Otherwise, my gut feeling is make it an
array and try to simplify things down.

**Comment by asika32764** [comment]
Use array will be much simpler at the getter and setter logic.

**Pull request merged**
